"""Changed the default values of some fields

Revision ID: 83b1f4c7bbec
Revises: 0902da57a42d
Create Date: 2023-10-11 20:22:55.539257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "83b1f4c7bbec"
down_revision: Union[str, None] = "0902da57a42d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
