"""Changed the default values of some fields

Revision ID: c2b5ba78e943
Revises: 3d7cc643c9dd
Create Date: 2023-10-11 20:39:15.843133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c2b5ba78e943"
down_revision: Union[str, None] = "3d7cc643c9dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
