"""empty message

Revision ID: 25e91aaa013b
Revises: 
Create Date: 2023-10-05 02:04:30.496513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25e91aaa013b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('test_id', sa.BIGINT(), nullable=False),
    sa.Column('test_name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('test_email', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.drop_table('client_masters')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('name', sa.VARCHAR(length=225), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('rollno', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yob', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('yog', sa.DATE(), autoincrement=False, nullable=True)
    )
    op.create_table('client_masters',
    sa.Column('client_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('state', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('pin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance_due', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_table('tests')
    # ### end Alembic commands ###
