"""Added new field slug

Revision ID: 2abd92675486
Revises: e30f8937054b
Create Date: 2023-11-01 20:16:33.218839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2abd92675486"
down_revision: Union[str, None] = "e30f8937054b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("events", sa.Column("slug", sa.String(), nullable=True))

    connection = op.get_bind()

    # 1. Copy the name to the slug column
    connection.execute(sa.text("UPDATE events SET slug = name"))

    # 2. Update the name column using the logic from unformat_event
    connection.execute(
        sa.text("UPDATE events SET name = REPLACE(INITCAP(name), '-', ' ')")
    )

    op.alter_column("events", "slug", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "slug")
    # ### end Alembic commands ###
