"""empty message

Revision ID: 8c73aac9fc55
Revises: 25e91aaa013b
Create Date: 2023-10-05 02:18:23.783546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c73aac9fc55'
down_revision: Union[str, None] = '25e91aaa013b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nontests',
    sa.Column('test_id_one', sa.BIGINT(), nullable=False),
    sa.Column('test_name_one', sa.VARCHAR(length=40), nullable=False),
    sa.Column('test_email_one', sa.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('test_id_one')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nontests')
    # ### end Alembic commands ###
